
CREATE DATABASE IF NOT EXISTS games;
USE games;

CREATE TABLE IF NOT EXISTS games.player (
  id INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
  email VARCHAR(100),
  password VARCHAR(45),
  nickname VARCHAR(45),
  registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
